### ISSUE TITLE
Newline Characters Inserted

### ISSUE THREAD

**Issue by Ken-Richard** [logstash-plugins/logstash-codec-multiline#14]
Newline Characters are being added to the output when using the multi-line input codec.

Steps to recreate: https://gist.github.com/Ken-Richard/2cef7035181269a68873

The gist creates a simple log stash config and then pushes the same line through. The gist checks for grokparsefailure and then prints the near by output. You can see the extra \n characters inserted into the middle of the string.

Remove the multiline input codec and the problem goes away.

Sample Output:

```
"@timestamp" => "2015-11-16T20:21:07.096Z",
   "message" => "[X7LXB\nQIYE63DEJCOQHUM] Started OPTIONS \"/content/4D076HQI8LUSHA833TL1\" for 10.230.64.67 at 2015-10-31 03:17:14 +0000\nLine2\nLine3",
  "@version" => "1",
      "tags" => [
    [0] "multiline",
    [1] "_grokparsefailure"
```

Possibly Similar Issue: https://github.com/elastic/logstash/issues/2925

OSX, Log Stash 2.0.0

**Comment by guyboertje** [comment]
@Ken-Richard - This is exactly how this codec works. It takes the matching set of subsequent lines and concatenates them to the message from the first line and creates one Event from that message.  Without this codec you would get an Event for each line.
https://www.elastic.co/guide/en/logstash/current/plugins-codecs-multiline.html
Unfortunately, there is a bug in the doc - it does not mention that the merged lines are separated by a newline character.
I think the newline separator best represents the data in its original form (as lines).

**Comment by Ken-Richard** [comment]
Thanks for taking a look. The extra newlines are being randomly inserted into content fields, in addition to the separator for merged lines.

Can you take a look at the script in the GIST? I think that shows the problem recreated in the simplest format.

SAMPLE INPUT:
X7LXBQIYE63DEJCOQHUM

SAMPLE OUTPUT:
X7LXB\nQIYE63DEJCOQHUM

**Comment by guyboertje** [comment]
@Ken-Richard - I will give it to you, it is a very subtle bug and in the stdin input.  The clue is in this line from the stdin input: `data = $stdin.sysread(16384)`. Your Gist is filling the stdin input, then piping that to LS. Each iteration of the ruby code adds 129 characters. After 129 iterations it has written more than 16384 characters.  When the stdin input reads 16384 characters and hands that to multiline, the data given is not aligned on an EOL boundary. This causes the multiline pattern to miss because the `[` was in the previous line and not at the beginning of a line.

I noticed the grok failures messages were
`"message" => "[\nX7LXBQIYE63DEJCOQHUM] ...` 
`"message" => "[X\n7LXBQIYE63DEJCOQHUM] ...`
`"message" => "[X7\nLXBQIYE63DEJCOQHUM] ...` 
the newlines were shifting to the right by one character.

**Comment by guyboertje** [comment]
@Ken-Richard - please open an issue on the stdin input repo and refer to this one then close this one.

**Comment by Ken-Richard** [comment]
Thanks! Before I do that can you answer a question about the code? I am not familiar with the mechanics and protocols of logstash plugins.

It looks like incoming data is added to the @buffer and then sent to logstash with the call:

```
event = LogStash::Event.new(LogStash::Event::TIMESTAMP => @time, "message" => @buffer.join(NL))
```

If the data comes in two chunks (based on stdin reading blocks instead of lines) then it appears that two entries for the line would be added to @buffer, and that the `join` about would add the extra newline.

One solution could be to retain the newline characters when the line is split, and remove the NL from the join statement.

Change

```
text.split("\n").each do |line|
```

to 

```
text.scan(/^.+[\r\n]*/).each do |line|
```

And then change

```
"message" => @buffer.join(NL)
```

to 

```
"message" => @buffer.join
```

Thought?

**Comment by swachter** [comment]
Hi,

I think I experience the same problem: under heavy load multiple log message are sent in a single TCP package over the wire. The messages are separated by 0xa characters. If a message does not fit into the package it is continued in the next package. After the multiline codec has processed the input, a '\n' character is inserted at the position where the log message was cut.

A workaround seems to be to use a multiline filter instead of a multiline codec.

**Comment by guyboertje** [comment]
@Ken-Richard - this codec must operate with other inputs. So changing this codec is not the direction to take. It is the **combination** of stdin input and this codec that is misbehaving.  For example, the combination of this codec and the file input does not exhibit the fault you have found.  Reason: the file input gets line oriented data from the `filewatch` library, so if this codec receives a line like this: `foo\nbar\nbaz` it is certain that `baz` is a full line.

In this case it is getting `...\nLine2\nLine3\n[X7L` and then `XBQIYE63DEJCOQHUM]...` where `[X7L` are the last 4 characters of the 32K read block.  After the split on NL it detects a pattern match. so `Line2` and `Line3` get appended to the event and the codec puts `[X7L` into the buffer **as a line** because it its expected to work with lines. When `XBQIYE63DEJCOQHUM]...` comes along it is buffered on a line by line basis. Now the buffer looks like this:

```
[X7L
XBQIYE63DEJCOQHUM]...
Line2
Line3
```

and next time like this:

```
[X7LX
BQIYE63DEJCOQHUM]...
Line2
Line3
```

The default codec for stdin is the line codec and it uses a `FileWatch::BufferedTokenizer` to line orient the data read by stdin.  Most, if not all, other inputs that use this codec are naturally line oriented.

The obvious solution is to do stdin input -> line codec -> multiline codec, but unfortunately we can't chain codecs (yet).

This is why we need a hack in stdin input to make it line oriented.

Moving the discussion to: https://github.com/logstash-plugins/logstash-input-stdin/issues/8

**Comment by TurboPunk** [comment]
This codec is not only misbehaving with stdin input, I have additional newlines while using tcp input.
Does tcp input also need to be made line oriented?

**Comment by guyboertje** [comment]
@TurboPunk - yes. Please create an issue on the tcp-input.

**Comment by hungnguyenmanh82** [comment]
this issue has been not fix for 6 years. logstash version 7.13.1, Tcp-input with Codec Multiline plugin => it allways insert random newline "\r\n" to some text line. I took me log to find out that.

**Comment by fly0512** [comment]
I ran into the same problem with the Logstash version 6.6.0, where random positions were occasionally added with \n symbols when using TCP inputs

**Comment by tammytankian** [comment]
I seems the problem continues... 
I was going crazy trying to understand what was happening until I found this thread. using TCP input and logstash 8.13
Any help would be highly appreciated
